language: python

python:
  - "2.7"

env:
  - VERSION="7.0" ODOO_REPO="odoo/odoo"
  - VERSION="7.0" ODOO_REPO="OCA/OCB"

virtualenv:
  system_site_packages: true

before_install:
  - sudo pip install GitPython bzr
  - sudo apt-get -y remove postgresql-9.1
  - sudo apt-get -y install bzr postgresql-9.3
  - sudo service postgresql start

install:
  - git clone https://github.com/OCA/web.git $HOME/web -b 7.0
  - bzr branch lp:openerp-french-localization/7.0 $HOME/openerp-french-localization
  - git clone https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly ${VERSION}
  - printf '[options]\n\nrunning_env = dev' > ${HOME}/.openerp_serverrc
  - sudo pip install cairosvg
  - sudo apt-get install wkhtmltopdf

script:
  - travis_run_tests ${VERSION}

after_success:
  coveralls

